---
- name: Check settings
  stat:
    path: "/usr/share/X11/xorg.conf.d/40-gpd-pocket2-monitor.conf"
  register: umpc

- name: Inject settings
  include: umpc.yml
  when: not umpc.stat.exists

- name: Disable touch screen configration
  file:
    path: "/etc/udev/rules.d/99-gpd-pocket2-touch.rules"
    state: absent

- name: Configure the greeter
  become: true
  copy:
    src: "{{ playbook_dir }}/files/slick-greeter.conf"
    dest: "/etc/lightdm/slick-greeter.conf"

- name: Set window-scaling-factor
  shell: "gsettings set org.gnome.settings-daemon.plugins.xsettings overrides \"{'Gdk/WindowScalingFactor': <2>}\""
  changed_when: false

- name: Rotate display
  copy:
    src: "{{ playbook_dir }}/files/monitors.xml"
    dest: "~/.config/monitors.xml"

