---
- name: Add key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://dl-ssl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- name: Install chrome
  become: true
  apt:
    name: google-chrome-stable
    state: present

