---
- name: Remove apps
  become: true
  apt:
    name:
      - firefox*
    state: absent
    purge: true

- name: Install apps
  become: true
  snap:
    name: shotcut
    classic: yes

- name: Install chrome
  include: chrome.yml

