- name: Install apps
  become: true
  apt:
    name:
      - handbrake
      - gparted
      - nomacs
      - rawtherapee
      - soundconverter
      - baobab
      - evince
      - asunder
      - ardour
      - gnome-boxes
      - firefox
      - timeshift
    state: present

- name: Install apps (snap, classic)
  become: true
  snap:
    name:
      - shotcut
      - blender
      - flutter
      - intellij-idea-community
      - android-studio
      - android-studio-canary
    classic: yes

- name: Install apps (snap)
  become: true
  snap:
    name:
      - gimp
      - qalculate
      - spotify
      - vlc

- name: Install chrome
  include: chrome.yml

- name: Install vscode
  include: vscode.yml

- name: Install slack
  include: slack.yml

- name: Install discord
  include: discord.yml

- name: Install ulauncher
  include: ulauncher.yml

- name: Install steam
  include: steam.yml

- name: Install zoom
  include: zoom.yml

