- name: Add repository
  become: true
  apt_repository:
    repo: ppa:agornostal/ulauncher 

- name: Install ulauncher
  become: true
  apt:
    name:
      - wmctrl
      - ulauncher
    state: present

