- name: Install tweak tool
  become: true
  apt:
    name:
      - gnome-tweak-tool
    state: present

- name: Setup keybindings
  include: keybind.yml

- name: Setup favorite apps
  include: favorite_apps.yml

- name: Setup display scaling
  include: scaling.yml

- name: Setup mice
  include: mouse.yml

- name: Setup theme
  include: theme.yml

