- name: Install themes
  become: true
  apt:
    name:
      - ubuntu-budgie-themes
      - budgie-wallpapers
    state: present

- name: Setup theme
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Pocillo'"

- name: Battery percentage
  dconf:
    key: /org/gnome/desktop/interface/show-battery-percentage
    value: 'true'

