- name: Install dev tools
  become: true
  apt:
    name:
      - cmake
      - libssl-dev
      - build-essential
      - ccache
    state: present

- name: Install X11 packages
  include: x11.yml

- name: Install GTK packages
  include: gtk.yml

