- name: Add repository
  become: true
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present

- name: Install golang
  become: true
  apt:
    name: golang-go
    state: present

- name: Export GOPATH
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: export GOPATH=$HOME/go
    create: yes

- name: Add to PATH
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: export PATH=$GOPATH/bin:$PATH
    create: yes

