- name: Check haskell
  command: which stack
  register: haskell
  changed_when: false
  ignore_errors: true

- name: Install GHC
  when: haskell.failed
  become: true
  apt:
    name:
      - ghc
    state: present

- name: Create temporary directory
  when: haskell.failed
  tempfile:
    state: directory
    suffix: haskell 
  register: haskell_tmp

- name: Download script
  when: haskell.failed
  get_url:
    dest: "{{ haskell_tmp.path }}/init.sh"
    url: https://get.haskellstack.org/

- name: Run script
  when: haskell.failed
  become: true
  command: "sh {{ haskell_tmp.path }}/init.sh"

- name: Cleanup temporary directory
  when: haskell.failed
  file:
    path: "{{ haskell_tmp }}"
    state: absent

