- name: Install common tools
  become: true
  apt:
    name:
      - vim
      - tmux
      - curl
      - cmake
      - libssl-dev
      - libx11-dev
      - libxcursor-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxi-dev
      - ibus-mozc
      - language-pack-gnome-ja
      - fonts-noto-cjk-extra
      - gnome-getting-started-docs-ja
      - gnome-user-docs-ja
    state: present

- name: Configure tmux
  become: true
  copy:
    src: "{{ playbook_dir }}/files/tmux.conf"
    dest: "/etc/tmux.conf"

- name: Install git
  include: git.yml

- name: Setup docker
  include: docker.yml
